//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionDetail
    {
        public int OptionDetailsId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public string PlaceHolder { get; set; }
        public Nullable<int> MinLength { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public string RegexPattern { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
