//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestionMapping
    {
        public int SurveyQuestionMappingId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> QuestionId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
